import React, { ReactElement } from 'react'
import Navbar from './Navbar'
import Head from 'next/head'


type LayoutProps = Required<{
    readonly children: ReactElement
  }>

function Layout({ children }: LayoutProps) {
  return (
<>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
        <Navbar />
        {children}
        
    </div>

    </>
    
  )
}

export default Layout

